/**
 * tests/helpers/fixtures.ts
 * Pre-seeded reference personas, mandi centers, operators, and MSP rates
 * matching ORIGINAL_REQUEST.md, PROJECT.md, and spec_domain.md.
 */

import { FarmerPersona, MandiCenter, MandiOperator, OfficialMspRate } from './types';

export const OFFICIAL_MSP_RATES: OfficialMspRate[] = [
  { cropKey: 'wheat', cropName: 'Wheat (गेहूं / గోధుమలు)', category: 'GRAINS', grade: 'FAQ', mspPerQuintal: 2275, maxMoistureFAQ: 12.0, maxMoistureGradeA: 10.0 },
  { cropKey: 'wheat', cropName: 'Wheat (गेहूं / గోధుమలు)', category: 'GRAINS', grade: 'Grade A', mspPerQuintal: 2300, maxMoistureFAQ: 12.0, maxMoistureGradeA: 10.0 },
  { cropKey: 'paddy', cropName: 'Paddy (धान / వరి)', category: 'GRAINS', grade: 'FAQ', mspPerQuintal: 2183, maxMoistureFAQ: 17.0, maxMoistureGradeA: 14.0 },
  { cropKey: 'paddy', cropName: 'Paddy (धान / వరి)', category: 'GRAINS', grade: 'Grade A', mspPerQuintal: 2203, maxMoistureFAQ: 17.0, maxMoistureGradeA: 14.0 },
  { cropKey: 'chana', cropName: 'Chana (चना / శనగలు)', category: 'PULSES', grade: 'FAQ', mspPerQuintal: 5440, maxMoistureFAQ: 10.0, maxMoistureGradeA: 8.5 },
  { cropKey: 'chana', cropName: 'Chana (चना / శనగలు)', category: 'PULSES', grade: 'Grade A', mspPerQuintal: 5500, maxMoistureFAQ: 10.0, maxMoistureGradeA: 8.5 },
  { cropKey: 'moong', cropName: 'Moong (मूंग / పెసలు)', category: 'PULSES', grade: 'FAQ', mspPerQuintal: 8558, maxMoistureFAQ: 10.0, maxMoistureGradeA: 8.0 },
  { cropKey: 'moong', cropName: 'Moong (मूंग / పెసలు)', category: 'PULSES', grade: 'Grade A', mspPerQuintal: 8650, maxMoistureFAQ: 10.0, maxMoistureGradeA: 8.0 },
  { cropKey: 'onion', cropName: 'Onion (प्याज़ / ఉల్లిపాయలు)', category: 'VEGETABLES_FRUITS', grade: 'FAQ', mspPerQuintal: 1800, maxMoistureFAQ: 15.0, maxMoistureGradeA: 12.0 },
  { cropKey: 'tomato', cropName: 'Tomato (टमाटर / టమోటాలు)', category: 'VEGETABLES_FRUITS', grade: 'FAQ', mspPerQuintal: 1500, maxMoistureFAQ: 20.0, maxMoistureGradeA: 15.0 },
  { cropKey: 'potato', cropName: 'Potato (आलू / బంగాళాదుంపలు)', category: 'VEGETABLES_FRUITS', grade: 'FAQ', mspPerQuintal: 1200, maxMoistureFAQ: 18.0, maxMoistureGradeA: 14.0 },
];

export const PRESEEDED_FARMERS: FarmerPersona[] = [
  {
    id: 'FARMER_001',
    name: 'Gurpreet Singh',
    district: 'Ludhiana',
    state: 'Punjab',
    aadhaarNumber: '548912345678',
    phone: '9814012345',
    landRecords: [
      {
        id: 'LR_001',
        khasraNumber: '142/1, 142/2',
        khatauniNumber: 'KH-00421',
        village: 'Rampur',
        tehsilSubDistrict: 'Ludhiana West',
        district: 'Ludhiana',
        state: 'Punjab',
        totalLandAreaAcres: 4.0,
        cropSeason: 'RABI_2024_25',
        verifiedSownCrop: 'wheat',
        sownAreaAcres: 4.0,
        mspProductivityNormQtlPerAcre: 25.0,
        maxProcurementQuotaQtl: 100.0,
        utilizedQuotaQtl: 0.0,
        remainingQuotaQtl: 100.0,
      },
    ],
    bankAccount: {
      bankName: 'Punjab National Bank',
      accountNumberMasked: 'XXXXXX4512',
      ifscCode: 'PUNB0012300',
    },
  },
  {
    id: 'FARMER_002',
    name: 'Venkata Ramana',
    district: 'Guntur',
    state: 'Andhra Pradesh',
    aadhaarNumber: '432187654321',
    phone: '9440198765',
    landRecords: [
      {
        id: 'LR_002',
        khasraNumber: '204/3',
        khatauniNumber: 'KH-00892',
        village: 'Dharmavaram',
        tehsilSubDistrict: 'Guntur Rural',
        district: 'Guntur',
        state: 'Andhra Pradesh',
        totalLandAreaAcres: 3.5,
        cropSeason: 'KHARIF_2024_25',
        verifiedSownCrop: 'paddy',
        sownAreaAcres: 3.5,
        mspProductivityNormQtlPerAcre: 28.0,
        maxProcurementQuotaQtl: 98.0,
        utilizedQuotaQtl: 20.0,
        remainingQuotaQtl: 78.0,
      },
    ],
    bankAccount: {
      bankName: 'State Bank of India',
      accountNumberMasked: 'XXXXXX8821',
      ifscCode: 'SBIN0004567',
    },
  },
  {
    id: 'FARMER_003',
    name: 'Ramesh Patel',
    district: 'Sehore',
    state: 'Madhya Pradesh',
    aadhaarNumber: '987654321012',
    phone: '9755011223',
    landRecords: [
      {
        id: 'LR_003',
        khasraNumber: '88/A, 89/B',
        khatauniNumber: 'KH-00109',
        village: 'Bilkisganj',
        tehsilSubDistrict: 'Sehore',
        district: 'Sehore',
        state: 'Madhya Pradesh',
        totalLandAreaAcres: 5.0,
        cropSeason: 'RABI_2024_25',
        verifiedSownCrop: 'chana',
        sownAreaAcres: 5.0,
        mspProductivityNormQtlPerAcre: 10.0,
        maxProcurementQuotaQtl: 50.0,
        utilizedQuotaQtl: 0.0,
        remainingQuotaQtl: 50.0,
      },
    ],
    bankAccount: {
      bankName: 'Bank of Baroda',
      accountNumberMasked: 'XXXXXX3390',
      ifscCode: 'BARB0SEHORE',
    },
  },
  {
    id: 'FARMER_004',
    name: 'Savitri Bai',
    district: 'Nashik',
    state: 'Maharashtra',
    aadhaarNumber: '876543210987',
    phone: '9822055667',
    landRecords: [
      {
        id: 'LR_004',
        khasraNumber: '51/2',
        khatauniNumber: 'KH-00714',
        village: 'Lasalgaon',
        tehsilSubDistrict: 'Niphad',
        district: 'Nashik',
        state: 'Maharashtra',
        totalLandAreaAcres: 2.0,
        cropSeason: 'RABI_2024_25',
        verifiedSownCrop: 'onion',
        sownAreaAcres: 2.0,
        mspProductivityNormQtlPerAcre: 80.0,
        maxProcurementQuotaQtl: 160.0,
        utilizedQuotaQtl: 40.0,
        remainingQuotaQtl: 120.0,
      },
    ],
    bankAccount: {
      bankName: 'Bank of Maharashtra',
      accountNumberMasked: 'XXXXXX7741',
      ifscCode: 'MAHB0000321',
    },
  },
  {
    id: 'FARMER_005',
    name: 'Balwan Singh',
    district: 'Karnal',
    state: 'Haryana',
    aadhaarNumber: '765432109876',
    phone: '9416044332',
    landRecords: [
      {
        id: 'LR_005',
        khasraNumber: '311/4',
        khatauniNumber: 'KH-00551',
        village: 'Nilokheri',
        tehsilSubDistrict: 'Karnal',
        district: 'Karnal',
        state: 'Haryana',
        totalLandAreaAcres: 6.0,
        cropSeason: 'RABI_2024_25',
        verifiedSownCrop: 'wheat',
        sownAreaAcres: 6.0,
        mspProductivityNormQtlPerAcre: 25.0,
        maxProcurementQuotaQtl: 150.0,
        utilizedQuotaQtl: 50.0,
        remainingQuotaQtl: 100.0,
      },
    ],
    bankAccount: {
      bankName: 'Canara Bank',
      accountNumberMasked: 'XXXXXX9912',
      ifscCode: 'CNRB0002100',
    },
  },
  {
    id: 'FARMER_006',
    name: 'Appa Rao',
    district: 'Warangal',
    state: 'Telangana',
    aadhaarNumber: '654321098765',
    phone: '9949088776',
    landRecords: [
      {
        id: 'LR_006',
        khasraNumber: '102/1',
        khatauniNumber: 'KH-00332',
        village: 'Narsampet',
        tehsilSubDistrict: 'Warangal Rural',
        district: 'Warangal',
        state: 'Telangana',
        totalLandAreaAcres: 3.0,
        cropSeason: 'RABI_2024_25',
        verifiedSownCrop: 'moong',
        sownAreaAcres: 3.0,
        mspProductivityNormQtlPerAcre: 6.5,
        maxProcurementQuotaQtl: 19.5,
        utilizedQuotaQtl: 0.0,
        remainingQuotaQtl: 19.5,
      },
    ],
    bankAccount: {
      bankName: 'Union Bank of India',
      accountNumberMasked: 'XXXXXX1154',
      ifscCode: 'UBIN0532145',
    },
  },
  {
    id: 'FARMER_007',
    name: 'Ram Kumar Maurya',
    district: 'Varanasi',
    state: 'Uttar Pradesh',
    aadhaarNumber: '543210987654',
    phone: '9450033221',
    landRecords: [
      {
        id: 'LR_007',
        khasraNumber: '45/9',
        khatauniNumber: 'KH-00912',
        village: 'Pindra',
        tehsilSubDistrict: 'Varanasi',
        district: 'Varanasi',
        state: 'Uttar Pradesh',
        totalLandAreaAcres: 1.5,
        cropSeason: 'ALL_SEASON',
        verifiedSownCrop: 'tomato',
        sownAreaAcres: 1.5,
        mspProductivityNormQtlPerAcre: 90.0,
        maxProcurementQuotaQtl: 135.0,
        utilizedQuotaQtl: 0.0,
        remainingQuotaQtl: 135.0,
      },
    ],
    bankAccount: {
      bankName: 'Central Bank of India',
      accountNumberMasked: 'XXXXXX6673',
      ifscCode: 'CBIN0281234',
    },
  },
  {
    id: 'FARMER_008',
    name: 'Mohan Lal',
    district: 'Agra',
    state: 'Uttar Pradesh',
    aadhaarNumber: '432109876543',
    phone: '9837022114',
    landRecords: [
      {
        id: 'LR_008',
        khasraNumber: '112/5',
        khatauniNumber: 'KH-00624',
        village: 'Fatehabad',
        tehsilSubDistrict: 'Agra',
        district: 'Agra',
        state: 'Uttar Pradesh',
        totalLandAreaAcres: 5.0,
        cropSeason: 'RABI_2024_25',
        verifiedSownCrop: 'potato',
        sownAreaAcres: 3.0,
        verifiedAcreage: 3.0,
        mspProductivityNormQtlPerAcre: 100.0,
        maxProcurementQuotaQtl: 300.0,
        maxProcurementQuotaQuintals: 300.0,
        utilizedQuotaQtl: 0.0,
        remainingQuotaQtl: 300.0,
      },
    ],
    bankAccount: {
      bankName: 'State Bank of India',
      accountNumberMasked: 'XXXXXX5520',
      ifscCode: 'SBIN0001144',
    },
  },
];

export const MANDI_CENTERS: MandiCenter[] = [
  {
    id: 'MND-LUD-01',
    name: 'Ludhiana Central Grain Mandi',
    district: 'Ludhiana',
    state: 'Punjab',
    latitude: 30.901,
    longitude: 75.8573,
    totalBays: 3,
    bays: [
      { id: 'BAY-LUD-01', bayNumber: 1, name: 'Bay 1 - Heavy Weighbridge', status: 'IDLE' },
      { id: 'BAY-LUD-02', bayNumber: 2, name: 'Bay 2 - Standard Weighbridge', status: 'IDLE' },
      { id: 'BAY-LUD-03', bayNumber: 3, name: 'Bay 3 - Express Weighbridge', status: 'IDLE' },
    ],
    activeStatus: true,
  },
  {
    id: 'MND-GNT-01',
    name: 'Guntur APMC Paddy Procurement Centre',
    district: 'Guntur',
    state: 'Andhra Pradesh',
    latitude: 16.3067,
    longitude: 80.4365,
    totalBays: 2,
    bays: [
      { id: 'BAY-GNT-01', bayNumber: 1, name: 'Bay 1 - North Gate', status: 'IDLE' },
      { id: 'BAY-GNT-02', bayNumber: 2, name: 'Bay 2 - South Gate', status: 'IDLE' },
    ],
    activeStatus: true,
  },
  {
    id: 'MND-SEH-01',
    name: 'Sehore Krishi Upaj Mandi',
    district: 'Sehore',
    state: 'Madhya Pradesh',
    latitude: 23.2032,
    longitude: 77.0844,
    totalBays: 2,
    bays: [
      { id: 'BAY-SEH-01', bayNumber: 1, name: 'Bay 1 - Main Yard', status: 'IDLE' },
      { id: 'BAY-SEH-02', bayNumber: 2, name: 'Bay 2 - Secondary Yard', status: 'IDLE' },
    ],
    activeStatus: true,
  },
  {
    id: 'MND-AGR-01',
    name: 'Agra Potato & Vegetable Mandi',
    district: 'Agra',
    state: 'Uttar Pradesh',
    latitude: 27.1767,
    longitude: 78.0081,
    totalBays: 2,
    bays: [
      { id: 'BAY-AGR-01', bayNumber: 1, name: 'Bay 1 - Cold Store Gate', status: 'IDLE' },
      { id: 'BAY-AGR-02', bayNumber: 2, name: 'Bay 2 - Processing Yard', status: 'IDLE' },
    ],
    activeStatus: true,
  },
];

export const MANDI_OPERATORS: MandiOperator[] = [
  { id: 'OP_001', employeeId: 'EMP-LUD-001', pin: '2026', name: 'Harpreet Sharma', assignedCenterId: 'MND-LUD-01' },
  { id: 'OP_002', employeeId: 'EMP-GNT-001', pin: '2026', name: 'Srinivas Rao', assignedCenterId: 'MND-GNT-01' },
  { id: 'OP_003', employeeId: 'EMP-SEH-001', pin: '2026', name: 'Vikram Joshi', assignedCenterId: 'MND-SEH-01' },
  { id: 'OP_004', employeeId: 'EMP-AGR-001', pin: '2026', name: 'Rajesh Verma', assignedCenterId: 'MND-AGR-01' },
];

export const TRANSLATION_DICTIONARY = {
  en: {
    appTitle: 'KisanJod',
    subTitle: 'Digital Mandi Procurement',
    verifyAadhaar: 'Verify Aadhaar',
    enterOtp: 'Enter 6-Digit OTP',
    yourTurn: 'Your Turn',
    liveEta: 'Live ETA',
    servingNow: 'Serving Now',
    farmersAhead: 'Farmers Ahead',
    turnNearingAlert: "Ahead farmer's processing is completing. Your turn will be in approximately 10 minutes. Please arrive at the bay holding area.",
    proceedToBay: 'Token {token}: Please proceed to {bay} for weighment & grading.',
    standbyMessage: 'Waiting for Next Gap',
  },
  hi: {
    appTitle: 'किसानजोड़',
    subTitle: 'डिजिटल मंडी खरीद मंच',
    verifyAadhaar: 'आधार सत्यापन',
    enterOtp: '6 अंकों का ओटीपी दर्ज करें',
    yourTurn: 'आपकी बारी',
    liveEta: 'अनुमानित समय',
    servingNow: 'वर्तमान सेवा',
    farmersAhead: 'आगे किसान',
    turnNearingAlert: 'आगे वाले किसान का काम पूरा हो रहा है। आपकी बारी लगभग 10 मिनट में आएगी। कृपया गेट पर तैयार रहें।',
    proceedToBay: 'टोकन {token}: कृपया तौल एवं जांच के लिए {bay} पर पहुंचे।',
    standbyMessage: 'अगली खाली जगह पर बारी',
  },
  te: {
    appTitle: 'కిసాన్ జోడ్',
    subTitle: 'డిజిటల్ మండి సేకరణ ప్లాట్‌ఫారమ్',
    verifyAadhaar: 'ఆధార్ ధృవీకరణ',
    enterOtp: '6 అంకెల OTP నమోదు చేయండి',
    yourTurn: 'మీ వంతు',
    liveEta: 'లైవ్ సమయం',
    servingNow: 'ప్రస్తుత టోకెన్',
    farmersAhead: 'ముందున్న రైతులు',
    turnNearingAlert: 'ముందున్న రైతు తూకం పూర్తవుతోంది. దాదాపు 10 నిమిషాల్లో మీ వంతు వస్తుంది. దయచేసి తూకం బే వద్దకు చేరుకోండి.',
    proceedToBay: 'టోకెన్ {token}: దయచేసి తూకం మరియు గ్రేడింగ్ కోసం {bay} వద్దకు వెళ్లండి.',
    standbyMessage: 'తదుపరి ఖాళీ సమయం కోసం వేచి ఉండండి',
  },
};
